/detect_node:
  ros__parameters:
    bottom_x: 394.0
    bottom_y: 118.0
    hue_white_h: 0.0
    hue_white_l: 0.0
    hue_yellow_h: 36.0
    hue_yellow_l: 8.0
    lightness_white_h: 255.0
    lightness_white_l: 220.0
    lightness_yellow_h: 255.0
    lightness_yellow_l: 240.0
    reliability_white_line: 100.0
    reliability_yellow_line: 100.0
    saturation_white_h: 0.0
    saturation_white_l: 0.0
    saturation_yellow_h: 80.0
    saturation_yellow_l: 8.0
    top_x: 328.0
    top_y: 128.0
